# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_system"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "(mostly)POSIX system routine interface"
categories = ["POSIX", "system"]
keywords = ["fortran", "system interface"]
homepage = "https://github.com/urbanjost/M_system.git"

[build]
auto-executables = false

[library]
source-dir="src"

[dev-dependencies]
   M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }
   M_time         = { git = "https://github.com/urbanjost/M_time.git" }
   M_process      = { git = "https://github.com/urbanjost/M_process.git" }

[[executable]]
name="penv"
source-dir="app"
main="penv.f90"
[executable.dependencies]
M_kracken = { git = "https://github.com/urbanjost/M_kracken.git" }
M_strings = { git = "https://github.com/urbanjost/M_strings.git" }
